config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  namespace :api do
    post 'login'  => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    resources :users
  end

  get     'login'    => 'session#new'
  post    'login'    => 'session#create'
  delete  'logout'   => 'session#destroy'

  resources :users

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'home#index'

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  validates :content, length: {minimum: 50, maximum: 250}

  #
  # def self.search(term)
  #   where('title LIKE ?', '%#{term}%')
  #   where('content LIKE ?', '%#{term}%')
  # end

  def self.search(term)
    where('title LIKE ?', "%#{term}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :access_tokens, class_name: 'Doorkeeper::AccessToken',
           foreign_key: :resource_owner_id, dependent: :destroy

  class << self
    def authenticate params
      user = User.find_by name: params[:name]
      return false unless user
      user.authenticate params[:password]
    end
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  before_action :doorkeeper_authorize!
  before_action :current_user

  def doorkeeper_unauthorized_render_options error
    {json: {errors: I18n.t("doorkeeper.errors.messages.unauthorized_client", uid: current_user&.id)}}
  end

  def current_user
    @current_user ||= User.find_by(id: doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Api::ApplicationController
  skip_before_action :doorkeeper_authorize!, only: :create

  def create
    user = User.authenticate users_params
    if user
      render json: {data: Api::GenerateTokenService.new(user).call}, status: 200
    else
      render json: {errors: I18n.t("errors.api.sessions_controller.login.failed")}, status: 400
    end
  end

  def destroy
    revoke_token_service = Api::RevokeTokenService.new doorkeeper_token.token
    revoke_token_service.execute
    if revoke_token_service.success?
      render json: {}, status: 200
    else
      render json: {errors: revoke_token_service.errors}, status: 400
    end
  end

  private
  def users_params
    params.require(:user).permit :name, :password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper

  before_action :require_login

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  def index
    @posts = Post.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:show, :index, :search]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:term]
      @posts = Post.search(params[:term]).order('created_at DESC')
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
      if @post.save
        flash[:success] = 'Post was successfully created.'
        redirect_to @post
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
      #TODO save user infor into session
      flash[:success] = 'Login success'
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = 'You are logged out'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'Register success'
      redirect_to users_path
    else
      flash[:success] = 'Register failed'
      render :new
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user.destroy
    redirect_to users_path
    format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    format.json { head :no_content }
  end

  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then 'alert alert-info'
      when 'success' then 'alert alert-success'
      when 'error' then 'alert alert-danger'
      when 'alert' then 'alert alert-warning'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end

  # GET current_user
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  # Check user has logged in before ?
  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="flexslider">
  <ul class="slides">
    <li>
      <%= image_tag '/slider/img1.jpg', class: 'img-responsive' %>
    </li>
    <li>
      <%= image_tag '/slider/img2.jpg', class: 'img-responsive' %>
    </li>
    <li>
      <%= image_tag '/slider/img3.jpg', class: 'img-responsive'%>
    </li>
  </ul>
</div>
<div class="container">
   <div class="row">
     <% @posts.each do |post|%>
        <div class="col-sm-4">
          <h3><%= post.title%></h3>
          <p><%= truncate(post.content, length: 150, :escape => false) %></p>
          <%= link_to 'Read More', post_path(post) %>
        </div>
     <%end%>
   </div>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Shimidzu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <%= form_tag(posts_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
        <%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2', placeholder: 'Input text to search' %>
        <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </div>
  <% if current_user %>
    <ul class="nav nav-tabs">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <%= image_tag('account.png', size: '40x40', alt: 'Account') %>
        </a>
        <div class="dropdown-menu">
          <%= link_to('Logout', logout_path, method: :delete, class: 'dropdown-item') %>
          <%= link_to('Profile', user_path(current_user), class: 'dropdown-item') %>
        </div>
      </li>
    </ul>
  <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-link">
          <a class="btn btn-primary" href="/login" role="button">Login</a>
        </li>
      </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/javascripts/ckeditor/config.js' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
            <%= value %>
          </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
            <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, id: :post_title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :content %>
      <%= form.cktext_area :content, id: :post_content, class: 'form-control', cols: 40 %>
    </div>

    <div class="actions">
      <%= form.submit '登録', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content.html_safe %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content.html_safe %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/session/new.html.erb
<div class="row">
  <h1 class="title">Login</h1>
</div>
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <%= form_for :session, url: login_path do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Enter your name', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: 'Enter your password',  class: 'form-control' %>
        </div>
        <div class="text-center">
          <%= f.submit 'Login', class: 'btn btn-info col-lg-12' %>
        </div>
        <div class="text-right">
          <%= link_to 'Register', new_user_path %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">LOGIN APP</h1>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">Welcome</label>
      <%= link_to current_user.name, user_path(current_user) %>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">List Users</label>
      <table class="table">
        <thead>
        <th>ID</th>
        <th>User Name</th>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.password_digest %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <h1 class="title">Register</h1>
</div>
<div class="row">
  <div class="col-lg">
    <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Name', class: 'col-md-6 control-label' %>
          <div class="col-md-6">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Enter user name' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Password', class: 'col-md-6 control-label' %>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'Password Confirmation', class: 'col-md-6 control-label' %>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter password confirmation' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-4">
            <%= f.submit 'Register', class: 'btn btn-success' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left col-lg-6", style="padding-left: 0px ">
        <label>User name: <%= @user.name %></label>
      </div>
      <% if current_user.id == @user.id %>
        <div class="text-right col-lg-6">
          <%= link_to 'Logout', logout_path, method: :delete %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-offset-3 col-lg-6">
      <%= link_to 'List Users', users_path %>
    </div>
  </div>
</div>